### ISSUE TITLE
missing file?

### ISSUE THREAD

**Issue by HenrikEckermann** [omixer/omixer-rpmR#7] opened 2022-12-14 06:32 UTC
Hi,

I tried using the R package on MacOS Montery. I installed omixer-rpmR first via CMD and then later using `install_github`.

When I run my code:

```r
library(tidyverse)
library(omixerRpm)

# load the KEGG orthologue table 
ko <- read.delim(
    "picrust2/data/KO_metagenome_out/pred_metagenome_unstrat_descrip.tsv",
    header = TRUE
    )

# pick most recent database 
listDB()
db <- loadDB(name = listDB()[1])

# calculate GBM abundance and store in df
gbm <- rpm(x = ko, module.db = db)
```

I get the following error:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "E1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:735)
        at java.base/java.lang.Double.valueOf(Double.java:698)
        at org.omixer.rpm.parsers.FunctionLineProcessor.process(FunctionLineProcessor.java:49)
        at org.omixer.utils.utils.FileUtils.readMatrix(FileUtils.java:235)
        at org.omixer.rpm.service.impl.ModuleManagerImpl.inferModules(ModuleManagerImpl.java:173)
        at org.omixer.rpm.core.InferenceApp.main(InferenceApp.java:252)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/var/folders/f5/rkv6j_sj3sd8_m591syph__r0000gn/T//Rtmp7iwQds/file104e361195d7c/modules.tsv': No such file or directory
```

I tried using `threads = 16, java.mem = 16` based on an earlier issue that was reported here but that does not help. Any ideas what could be the issue?

**Comment by omixer** [comment] 2022-12-15 06:42
@HenrikEckermann 

Hi Henrik,  

Looking at the first error message, there is a `NumberFormatException` caused by `E1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]`. I guess your second column has a KO description and should be removed. Could you please double check that your input file is well formatted? Please see this file for an example https://github.com/omixer/omixer-rpmR/blob/master/test/matrix.tsv.
Sorry for the misleading error, will improve it in a future release.

Another thing, I noticed in your code below that you are trying to load the latest database
```
# pick most recent database 
listDB()
db <- loadDB(name = listDB()[1])
```
However this will load `GBMs.v1.0` which is a Gut Brain Module database, but if you are looking for a gut metabolic database you have to load `GMMs.v1.07`

Please refer to the links below for the details of each database!

Gut Brain Modules, [Valles-Colomer et al. 2019](https://www.nature.com/articles/s41564-018-0337-x), The neuroactive potential of the human gut microbiota in quality of life and depression, Nature Microbiology 2019.
Gut Metabolic Modules, [Vieira-Silva et al. 2016](https://www.nature.com/articles/nmicrobiol201688), Species-function relationships shape ecological properties of the human gut microbiome, Nature Microbiology 2016.


I hope this helps! 
Please let me know if you still face any issues after fixing the input file format.

Best regards,
Youssef

**Comment by HenrikEckermann** [comment] 2022-12-16 08:37
ah damn. Indeed that was the problem. I should have noticed that, sorry. Thanks for the hint with the database. I actually wanted to pick the GBM but the comment was misleading.

Should I close the issue or do you want to leave it open to enhance the error message?

**Comment by omixer** [comment] 2022-12-16 12:40
Glad to know it works... I created a branch and will close the issue with a pull request, so please keep it open!
Thanks

**Closed as completed** 2022-12-16 13:44 UTC
Labels: enhancement
